version: '2.3'

services:
  task:
    container_name: zero_pwn
    image: zero_pwn
    build: service
    restart: always
    ports:
      - 33876:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
