FROM node:10-alpine

COPY static/ /app/static
COPY app.js /app
COPY package.json /app
COPY node-entrypoint.sh /app

WORKDIR /app

RUN	npm install

EXPOSE 3000

ENTRYPOINT [ "/bin/sh", "/app/node-entrypoint.sh" ]
