version: "3.9"
services:
  squid:
    build: ./backend
    container_name: backend_squid
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "8100:80"
    deploy:
      resources:
        limits:
          memory: 4G
