version: '2.3'

services:
  task:
    container_name: amaze
    image: amaze
    build: service
    restart: always
    ports:
      - 42069:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
