version: '2.3'

services:
  task:
    container_name: heap_pwn
    image: heap_pwn
    build: service
    restart: always
    ports:
      - 20000:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
