version: "3.9"
services:
  db:
    image: postgres:9.4
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
    ports:
        - "127.0.0.1:5432:5432"
    deploy:
      resources:
        limits:
          memory: 5G

  web:
    build: .
    restart: always
    ports:
      - 8002:5000
    depends_on:
      - db
    links:
      - db
    deploy:
      resources:
        limits:
          memory: 3G
